# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67bc916fb2ef003a363406841560542b0337e63c412408d03516f7ecbc3d497ee1a9ecf4716f9ad239dd0d255a3b8e1ae11e0b2b2db44d1f1f0cd2bc4a920024

test:
  secret_key_base: 488dac1868cd28e658dad2155b41962ebdf30ebdee49647dcf17be8e9b3e379822827e9688de80fc2fb7d9806d110aaa76e184288b436366540cf85d75095bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
